[tool.poetry]
name = "fastapi-azure-app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.0"
uvicorn = "^0.27.0"

[tool.poetry.dev-dependencies]
pytest = "^8.0"
httpx = "^0.27.0"
pytest-cov = "^5.0"
codespell = "^2.2"
coverage = "^7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
